export const cleanGeneratedHtml = (html: string): string => {
  let cleaned = html;
  
  cleaned = cleaned.replace(/^```(?:html|json|markdown|)?\s*/gi, "");
  cleaned = cleaned.replace(/\s*```$/gi, "");
  cleaned = cleaned.replace(
    /^(?:\s*(?:Вот|Создал|Написал|Готово|Статья|Код|HTML|Вот статья|Результат|Генерация|Сгенерировано)[:\s\-]*\n?)+/gi, 
    ""
  );
  cleaned = cleaned.replace(
    /(?:\n\s*)?(?:Создано с помощью|Generated by|Автор|Это статья создана|AI помощник|Искусственный интеллект).*$/gi, 
    ""
  );
  cleaned = cleaned.trim();
  
  const htmlStartMatch = cleaned.match(/<[^>]+>/);

  if (htmlStartMatch) {
    const startIndex = cleaned.indexOf(htmlStartMatch[0]);
    if (startIndex > 0) cleaned = cleaned.substring(startIndex);
  }
  
  if (!cleaned.match(/<[^>]+>/)) cleaned = `<p>${cleaned}</p>`;
  cleaned = cleaned.trim();
  return cleaned;
};